# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finderUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
import sys
from designeroutput import Ui_MainWindow
import argparse

class MyApp(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None, comp=None, db = None, cache = False):
        super(MyApp, self).__init__(parent)
        self.setupUi(self,comp,db,cache)

if __name__ == "__main__":
    parser= argparse.ArgumentParser()
    parser.add_argument("--db",help="Folder with known songs", required=True)
    parser.add_argument("--window-size",help="FFT window size in seconds",type=float,default=10.0)
    parser.add_argument("--window-overlap",help="FFT window overlap with last sample in seconds",type=float,default=2.0)
    parser.set_defaults(algorithm="gzip")
    parser.add_argument("--gzip",dest="algorithm",action="store_const",const="gzip")
    parser.add_argument("--lzma",dest="algorithm",action="store_const",const="lzma")
    parser.add_argument("--bzip2",dest="algorithm",action="store_const",const="bzip2")
    args = parser.parse_args()

    if args.algorithm == "gzip":
        from gzip import compress
    elif args.algorithm =="lzma":
        from lzma import compress
    elif args.algorithm =="bzip2":
        from bz2 import compress
    else:
        raise Exception("Unknown compression algorithm")
        
    app = QApplication(sys.argv)
    form = MyApp(comp=compress,db=args.db, cache= True)
    form.show()
    sys.exit(app.exec_())